version: '3.8'

services:
  auth:
    container_name: crm_auth
    build:
      # El contexto es el directorio raíz (donde está este archivo).
      context: .
      # La ruta explícita al Dockerfile que debe usar.
      dockerfile: ./auth-service/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://consilium_user:supersecretpassword@crm_db:5432/consilium_db
      - PORT=3000
      - JWT_SECRET=este-es-un-secreto-muy-largo-y-dificil-de-adivinar
    depends_on:
      - db
    networks:
      # Lo conectamos a ambas redes
      - proxy-net
      - crm-internal

  db:
    container_name: crm_db
    build:
      context: ./database
      # La ruta explícita al Dockerfile que debe usar.
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=consilium_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=consilium_db
    # SECCIÓN DE VOLÚMENES PARA LA BASE DE DATOS (ESTA ES LA CORRECTA)
    volumes:
      # Este volumen guarda los datos de la BD de forma persistente
      - pgdata:/var/lib/postgresql/data
    networks:
      - crm-internal

# CLAVE: Definimos el volumen 'pgdata' para que Docker lo gestione
volumes:
  pgdata:

networks:
  proxy-net:
    external: true
  crm-internal:
    driver: bridge
