version: '3.8'

services:
  auth:
    container_name: crm_auth
    build:
      # El contexto es el directorio raíz (donde está este archivo).
      context: .
      # La ruta explícita al Dockerfile que debe usar.
      dockerfile: ./auth-service/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://consilium_user:supersecretpassword@crm_db:5432/consilium_db
      - PORT=3000
    depends_on:
      db:
        # LÍNEA MODIFICADA: Ahora 'auth' esperará a que 'db' esté saludable
        condition: service_healthy
    networks:
      # Lo conectamos a ambas redes
      - proxy-net
      - crm-internal

  db:
    image: postgis/postgis:15-3.4
    container_name: crm_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=consilium_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=consilium_db
    networks:
      # La DB solo necesita estar en la red interna
      - crm-internal
    healthcheck:
      # pg_isready es una utilidad de postgres para comprobar si el servidor está aceptando conexiones
      test: ["CMD-SHELL", "pg_isready -U consilium_user -d consilium_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy-net:
    external: true
  crm-internal:
    driver: bridge
