version: '3.8'

services:
  # Servicio de Autenticación
  auth:
    build:
      context: ./auth-service
    container_name: crm_auth
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://consilium_user:supersecretpassword@crm_db:5432/consilium_db
      - PORT=3000
    volumes:
      # Monta todo el directorio del servicio para desarrollo en tiempo real
      - ./auth-service:/usr/src/app
      # Usa un volumen anónimo para proteger los node_modules instalados dentro del contenedor
      - /usr/src/app/node_modules
    networks:
      - proxy-net
    depends_on:
      - db

  # Base de Datos PostgreSQL
  db:
    image: postgis/postgis:15-3.4
    container_name: crm_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=consilium_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=consilium_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - proxy-net

volumes:
  pgdata:

networks:
  proxy-net:
    external: true
